# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aggregations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61ggregations.proto\x12\x0b\x61ggregation\"#\n\x12\x41ggregationRequest\x12\r\n\x05input\x18\x01 \x01(\t\"$\n\x13\x41ggregationResponse\x12\r\n\x05value\x18\x01 \x01(\x02\x32\x65\n\x0b\x41ggregation\x12V\n\x0fSendAggregation\x12\x1f.aggregation.AggregationRequest\x1a .aggregation.AggregationResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aggregations_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AGGREGATIONREQUEST._serialized_start=35
  _AGGREGATIONREQUEST._serialized_end=70
  _AGGREGATIONRESPONSE._serialized_start=72
  _AGGREGATIONRESPONSE._serialized_end=108
  _AGGREGATION._serialized_start=110
  _AGGREGATION._serialized_end=211
# @@protoc_insertion_point(module_scope)
